import os

import requests

from dotenv import load_dotenv


load_dotenv()

headers = {
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9',
    'access-control-allow-headers': 'Content-Type',
    'access-control-allow-origin': '*',
    'cache-control': 'no-cache',
    'content-type': 'application/json; charset=UTF-8',
    'origin': 'https://www.chrono24.com',
    'pragma': 'no-cache',
    'priority': 'u=1, i',
    'referer': 'https://www.chrono24.com/',
    'sec-ch-ua': '"Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36',
}

json_data = {
    'client_info': {
        'riskified_cookie': 'gueldyqi84kqjxa6ezswbqmcc8ntmy',
        'error': False,
        'payload': 'TJCdTJyIGb0FTJyITJBNTM3ITJDJTJyIGdtlXZvpmblUjMlI0MtEzMwATJDJTJyIGdtlXZ0NWYw1TJyITJBNTJyITM1cDM3gDN2cDMzAiNyUiMyUyQyUmMhNncfRWalQjMlI0MlEjM1IWOwQTNjBCM50TNwgTL2QTYtITO5IiY10jYldDO0AmNzUGNlEjMlIkMlMjMzJGaw92XklTJyITJBNTJyI3d3dmLoNmcu9zb0ImLvNSbyUiMyUyQyUnMlJmZyVmcyVTJyITJBNTJyITJyITJDJTJyIHalJiZyUiMzUSQyUmM0hHdzBTJBNTJGJTJGJ3d3dmLoNmcu9zb0ImLvNSbyUnRvJGb4VTJGJmcs9XZtgGZ5FGdu9SYt0TLxEjNxUWOuxWLl1GdvVmc0lSZk1WasFWLl5ydy0DMzISLp1DZxMDM1ETNzMmL0hSbzUnRlNXYjJEahh2clg0MjRDN1cTZxclYX9UezYETl8jMwZ3blM0MyQiMyUmNhNGdsF2bUdXZ0NmQkF2ZlU0MUR1QUJzXxA2Xpx3cpRmbfdHd1JSZyUiMyUyQyUnMpJ2cptmZllFZj92br9WalUjMlI0MlEjMnJWdsVHZxlTa0g3aqFGe2EXZzp2dxJWbjNGO05XblkjMlIkMlMjMjJ2bvxlck9XZ0BCayUiMzUTQ0ITJDJTJyIGcnFVZp9CZyUiMzUSQyUmMxojb4lydyUiMyUyQyUnMoN3blAjMlI0MlEjMjJHavJmby8CNj52bl0jMlIkMlMjMoJXYkJ2dyFVZj92bj5XdyJWZj5SeyUiMzUTQ0ETJDJTJyIGazF3XvRWdoNTJyITJBNmZsF2clUkMlMjMoJXa0N3b5J2Xlxmb0dCayUiMzUTQlIkMlMjMkJ2b1NWbuVFd09XasRSZyUiMzUSQyUlMvJGb4VTJwIGR5FGdu9SYyUCMl0jMxATM1YTMMliTyUEMl1GdvVmc0lSZyUEMpRWYlwjMOBVRlcjMyADMzITJwImZy9TJwITJ0ITMwETJDJDMwATJwImZy9TJwI2csFSZyUGMyZ2bl0jMhBTJwIHV1J3clRCZyUFMlNGblxicyUGMu9TJwI2Qyh2bv5jMlQjMlIkMlMjMjJ2bz52blx2Xzp2XlhXYfB2c6lVZs9Wap1CdyUiMzUTQ3MjNwADMwADMlAkMlMjMjJ2bz52blx3XzVWZfRnafNGahVFcz9XalpTJyITJBNjM3EDMwADMlAkMlMjMjJ2bz52blx3XvRGdsF2Xzp2XlhXYfB2c6lSZyUiMzUTQzMTMwADMwATJDJTJyImY0FGdyVVej9GayF2ZulyZyUiMzUWQhZHblNTJDJTJyImY0FGdyVVes9XZlZCbyUiMzUTQuAzNlMkMlMjMiJXY0RXZ5J2XpR2coNXYnJWan53XpRWblUjMlI0MyEjN4gCMyUyQyUmMulXapRWYfx2Yv92all3X0NXYlRzXlAjMlI0MlEjMoJHdwRTJyITJDJTJyIWap5GdhlFbj92br9WafV3chRGdfVSMyUiMzUSQyUnMlN3cpN2bl4jMlIkMlMjMiJmc392cyVTJyITJBNTJCdTJyIHcvJHZjVHd1NiYyUiMzUSQyUjMwIDMwMTM3ATJyITJDJTJyIXafN3byBTJyITJBNmZsF2clUkMlMjMpJ1cm9XalJmZ49TJyITJBNmZsF2clUkMlMjMlJlds9WZl4jMlI0MzEyM3UCRyUyQyUmMz9TJyITJBNTJCdTJyIGchxGdvZmcl0jMlI0MlEjMNJWYJNnblRCbyUiM3UCRyUyQyUnMldmYsdTJyITJBNTJCdTJyImduVGZy9TJyITJBNTJyI2Rv92ZlxTJwIWSj5iLyUCMBhHcsBSZlkjMlIkMlMjMyJWZk5XZlJicyUiMzUSQyUkMOF0RFxTJwIEKwFGclxTJDJTJwIUQH5ETlUjMNBXZhRCbyUFMlJmblRmcyVTJBNTJwIXQwBGblUjMNByMyUEMh1CeyUyQyUFMuV3clB2YmlWakVTJwImVyV2cvliblkjMlI0NlQkMlMjMyJXZvNHb0VWau9TJyITJBNTJCdTJyIHZyBTJyITJBNiMyUyQyUnMjNmclVmblgjMlI0MxEDMwgTJDJTJyI2cyNWZuVydyUiMzUTQ5EjMlAkMlMjMhJmdpFGblgjMlI0M5ETOlYkMlMjMhJmdpFHblcjMlI0MxETOwITJDJTJyIWau5XZoJTJyITJBNTMwUTJDJTJyIWau5XZ3JTJyITJBNTMykCMyUyQyUmM19GdyVCayUiMzUTQ5kiNyUyQyUmM19GdyVydyUiMzUTQ5EjMlA0NlQkMlMjMkJXYlR3X0NmculyZyUiMzUSQyUlMldCZyUEM1pibyUDM1ITJwIjMyASNyUDMzETJBNDMlY0MwECMyUEMNdCVw0TNwATJwIEKlNnbyRWYlwjMEBXYslWaodCdyUFMpRWbpUTJyITJDJTJyIWa05CbyUiMzUSQ3UiQyUmMvx2YsFSZyUiMzUSQyUmMuVVLTVTJyITJDJTJyInbtV3X5NycyUiMzUSQyUmMhxGdl4jMlIkMlMjMjJWYlwjMlI0MlEjMnJmcnV3b5JTJyITJDJTJyIHdlojMlI0MlEjMBJWbyVWahNTJGJ2Qph2YnFybyUiM3UCRyUyQyUmMvR2ds5War5TJyITJBNTMlAkMlMjMuJXYfZGc1xTJyITJBNTJyIEUGRTJwImVll2dyVTJDJ2Qyh2bl1TJwIEUGRTJwImVll2dyVTJDJ2Qyh2bp1Wdl0jMQBERlYjMWBWa3VXZlIkMNNWayN3bvNnZlQjMFBGZldTJwIEUGRTJwImVll2dyVTJDJ2ViV2S0lTJwInYpVHbtQWal4jMQBERlYjMlIkMlMjMuJXYfZGbuFyZyUiMzUSQyUmMuVVLTVTJyITJDJTJyIGcnFVZs9WYn5WdnFVZk9XYhRTJyITJBNTJCdTJyIGcnFVZs9WYn5WdnFSZyUiMzUSQyUmMuVTJyITJDJTJyIGazF3XyRWYz5Gb0FWau9TJyITJBNmZsF2clU0NlQkMlMjMjJHafJ2a5VycyUiMzUSQyUmMvxWYURWal1ycyU2QzNSayU2QwFCcyUiMyUyQyUmMul2Yn9mb0lybyUiMzUSQ3UiQyUnMhNmZyFSayUiMzUWQhZHblNTJDJTJyI2Yyh2bl13X1F3bhRTJyITJBNTM5EzNzEDM5gTO1QiNyUyQyUnMlNncpZ2YfV2dy92ayV3XuVGZmVWal5CZyUiMzUWQhZHblNTJDJTJyIXafNnYhJmdlUjMlI0MmFWYzxSZ3UCR3UAR==',
    },
}

def get_proxies():
    # proxy_user = os.getenv("BRIGHTDATA_RESIDENTIAL_PROXY_USER")
    # proxy_pass = os.getenv("BRIGHTDATA_RESIDENTIAL_PROXY_PASSWORD")

    proxy_user = os.getenv("BRIGHTDATA_DATACENTER_PROXY_USER")
    proxy_pass = os.getenv("BRIGHTDATA_DATACENTER_PROXY_PASSWORD")

    proxy_host = os.getenv("BRIGHTDATA_RESIDENTIAL_PROXY_HOST")
    proxy_port = os.getenv("BRIGHTDATA_RESIDENTIAL_PROXY_PORT")

    proxies = {'http': f'http://{proxy_user}:{proxy_pass}@{proxy_host}:{proxy_port}',
                'https': f'http://{proxy_user}:{proxy_pass}@{proxy_host}:{proxy_port}'}
    return proxies

def get_proxy(proxy_type: str = 'http'):
    proxies = get_proxies()
    return proxies.get(proxy_type, proxies[proxy_type])


response = requests.post('https://c.riskified.com/v2/client_infos',
                         headers=headers,
                         json=json_data,
                        proxies=get_proxies(),
                        verify=False)

print (response)

# Note: json_data will not be serialized by requests
# exactly as it was in the original request.
#data = '{"client_info":{"riskified_cookie":"gueldyqi84kqjxa6ezswbqmcc8ntmy","error":false,"payload":"TJCdTJyIGb0FTJyITJBNTM3ITJDJTJyIGdtlXZvpmblUjMlI0MtEzMwATJDJTJyIGdtlXZ0NWYw1TJyITJBNTJyITM1cDM3gDN2cDMzAiNyUiMyUyQyUmMhNncfRWalQjMlI0MlEjM1IWOwQTNjBCM50TNwgTL2QTYtITO5IiY10jYldDO0AmNzUGNlEjMlIkMlMjMzJGaw92XklTJyITJBNTJyI3d3dmLoNmcu9zb0ImLvNSbyUiMyUyQyUnMlJmZyVmcyVTJyITJBNTJyITJyITJDJTJyIHalJiZyUiMzUSQyUmM0hHdzBTJBNTJGJTJGJ3d3dmLoNmcu9zb0ImLvNSbyUnRvJGb4VTJGJmcs9XZtgGZ5FGdu9SYt0TLxEjNxUWOuxWLl1GdvVmc0lSZk1WasFWLl5ydy0DMzISLp1DZxMDM1ETNzMmL0hSbzUnRlNXYjJEahh2clg0MjRDN1cTZxclYX9UezYETl8jMwZ3blM0MyQiMyUmNhNGdsF2bUdXZ0NmQkF2ZlU0MUR1QUJzXxA2Xpx3cpRmbfdHd1JSZyUiMyUyQyUnMpJ2cptmZllFZj92br9WalUjMlI0MlEjMnJWdsVHZxlTa0g3aqFGe2EXZzp2dxJWbjNGO05XblkjMlIkMlMjMjJ2bvxlck9XZ0BCayUiMzUTQ0ITJDJTJyIGcnFVZp9CZyUiMzUSQyUmMxojb4lydyUiMyUyQyUnMoN3blAjMlI0MlEjMjJHavJmby8CNj52bl0jMlIkMlMjMoJXYkJ2dyFVZj92bj5XdyJWZj5SeyUiMzUTQ0ETJDJTJyIGazF3XvRWdoNTJyITJBNmZsF2clUkMlMjMoJXa0N3b5J2Xlxmb0dCayUiMzUTQlIkMlMjMkJ2b1NWbuVFd09XasRSZyUiMzUSQyUlMvJGb4VTJwIGR5FGdu9SYyUCMl0jMxATM1YTMMliTyUEMl1GdvVmc0lSZyUEMpRWYlwjMOBVRlcjMyADMzITJwImZy9TJwITJ0ITMwETJDJDMwATJwImZy9TJwI2csFSZyUGMyZ2bl0jMhBTJwIHV1J3clRCZyUFMlNGblxicyUGMu9TJwI2Qyh2bv5jMlQjMlIkMlMjMjJ2bz52blx2Xzp2XlhXYfB2c6lVZs9Wap1CdyUiMzUTQ3MjNwADMwADMlAkMlMjMjJ2bz52blx3XzVWZfRnafNGahVFcz9XalpTJyITJBNjM3EDMwADMlAkMlMjMjJ2bz52blx3XvRGdsF2Xzp2XlhXYfB2c6lSZyUiMzUTQzMTMwADMwATJDJTJyImY0FGdyVVej9GayF2ZulyZyUiMzUWQhZHblNTJDJTJyImY0FGdyVVes9XZlZCbyUiMzUTQuAzNlMkMlMjMiJXY0RXZ5J2XpR2coNXYnJWan53XpRWblUjMlI0MyEjN4gCMyUyQyUmMulXapRWYfx2Yv92all3X0NXYlRzXlAjMlI0MlEjMoJHdwRTJyITJDJTJyIWap5GdhlFbj92br9WafV3chRGdfVSMyUiMzUSQyUnMlN3cpN2bl4jMlIkMlMjMiJmc392cyVTJyITJBNTJCdTJyIHcvJHZjVHd1NiYyUiMzUSQyUjMwIDMwMTM3ATJyITJDJTJyIXafN3byBTJyITJBNmZsF2clUkMlMjMpJ1cm9XalJmZ49TJyITJBNmZsF2clUkMlMjMlJlds9WZl4jMlI0MzEyM3UCRyUyQyUmMz9TJyITJBNTJCdTJyIGchxGdvZmcl0jMlI0MlEjMNJWYJNnblRCbyUiM3UCRyUyQyUnMldmYsdTJyITJBNTJCdTJyImduVGZy9TJyITJBNTJyI2Rv92ZlxTJwIWSj5iLyUCMBhHcsBSZlkjMlIkMlMjMyJWZk5XZlJicyUiMzUSQyUkMOF0RFxTJwIEKwFGclxTJDJTJwIUQH5ETlUjMNBXZhRCbyUFMlJmblRmcyVTJBNTJwIXQwBGblUjMNByMyUEMh1CeyUyQyUFMuV3clB2YmlWakVTJwImVyV2cvliblkjMlI0NlQkMlMjMyJXZvNHb0VWau9TJyITJBNTJCdTJyIHZyBTJyITJBNiMyUyQyUnMjNmclVmblgjMlI0MxEDMwgTJDJTJyI2cyNWZuVydyUiMzUTQ5EjMlAkMlMjMhJmdpFGblgjMlI0M5ETOlYkMlMjMhJmdpFHblcjMlI0MxETOwITJDJTJyIWau5XZoJTJyITJBNTMwUTJDJTJyIWau5XZ3JTJyITJBNTMykCMyUyQyUmM19GdyVCayUiMzUTQ5kiNyUyQyUmM19GdyVydyUiMzUTQ5EjMlA0NlQkMlMjMkJXYlR3X0NmculyZyUiMzUSQyUlMldCZyUEM1pibyUDM1ITJwIjMyASNyUDMzETJBNDMlY0MwECMyUEMNdCVw0TNwATJwIEKlNnbyRWYlwjMEBXYslWaodCdyUFMpRWbpUTJyITJDJTJyIWa05CbyUiMzUSQ3UiQyUmMvx2YsFSZyUiMzUSQyUmMuVVLTVTJyITJDJTJyInbtV3X5NycyUiMzUSQyUmMhxGdl4jMlIkMlMjMjJWYlwjMlI0MlEjMnJmcnV3b5JTJyITJDJTJyIHdlojMlI0MlEjMBJWbyVWahNTJGJ2Qph2YnFybyUiM3UCRyUyQyUmMvR2ds5War5TJyITJBNTMlAkMlMjMuJXYfZGc1xTJyITJBNTJyIEUGRTJwImVll2dyVTJDJ2Qyh2bl1TJwIEUGRTJwImVll2dyVTJDJ2Qyh2bp1Wdl0jMQBERlYjMWBWa3VXZlIkMNNWayN3bvNnZlQjMFBGZldTJwIEUGRTJwImVll2dyVTJDJ2ViV2S0lTJwInYpVHbtQWal4jMQBERlYjMlIkMlMjMuJXYfZGbuFyZyUiMzUSQyUmMuVVLTVTJyITJDJTJyIGcnFVZs9WYn5WdnFVZk9XYhRTJyITJBNTJCdTJyIGcnFVZs9WYn5WdnFSZyUiMzUSQyUmMuVTJyITJDJTJyIGazF3XyRWYz5Gb0FWau9TJyITJBNmZsF2clU0NlQkMlMjMjJHafJ2a5VycyUiMzUSQyUmMvxWYURWal1ycyU2QzNSayU2QwFCcyUiMyUyQyUmMul2Yn9mb0lybyUiMzUSQ3UiQyUnMhNmZyFSayUiMzUWQhZHblNTJDJTJyI2Yyh2bl13X1F3bhRTJyITJBNTM5EzNzEDM5gTO1QiNyUyQyUnMlNncpZ2YfV2dy92ayV3XuVGZmVWal5CZyUiMzUWQhZHblNTJDJTJyIXafNnYhJmdlUjMlI0MmFWYzxSZ3UCR3UAR=="}}'
#response = requests.post('https://c.riskified.com/v2/client_infos', headers=headers, data=data)